create table if not exists atribuicoes (
	id varchar(20) not null,
	nome varchar(50) not null,
	situacao boolean default true not null,
	primary key (id)
);

create table if not exists cartorios (
	id bigint generated by default as identity,
	nome varchar(150) not null,
	observacao varchar(250),
	situacao_id varchar(20) not null,
	primary key (id)
);

create table if not exists cartorios_atribuicoes (
	cartorios_id bigint not null,
	atribuicoes_id varchar(20) not null
);

create table if not exists situacoes (
	id varchar(20) not null,
	nome varchar(50) not null,
	primary key (id)
);

alter table atribuicoes
	add constraint uk_atribuicoes_nome unique (nome);

alter table cartorios
	add constraint uk_cartorios_nome unique (nome);

alter table situacoes
	add constraint uk_situacoes_nome unique (nome);

alter table cartorios
	add constraint fk_situacao
	foreign key (situacao_id)
	references situacoes;

alter table cartorios_atribuicoes
	add constraint fk_atribuicoes
	foreign key (atribuicoes_id)
	references atribuicoes;

alter table cartorios_atribuicoes
	add constraint fk_cartorios
	foreign key (cartorios_id)
	references cartorios;